"""Mirror of Android's device audit-action vocabulary. Read-only data, not derived, not guessed.

Source of truth: app/src/main/java/com/example/samdapp/domain/audit/AuditLogger.kt, the
`AuditAction` enum, produced by the 2026-08-17 audit-logging-discipline session (PROGRESS.md,
"Android: AuditAction as the single source of truth for audit logging"). That session made
`AuditLogger.log()` accept only an `AuditAction` member, closing every call site that used to pass
a free-text string, so this list is now exhaustive rather than a best-effort subset.

This file must be regenerated by hand whenever the Android enum changes: add a value here, add
the matching value there, in the same commit. tests/test_sync.py asserts this file equals
app.services.sync's accepted device set (so the two backend-side copies cannot drift from each
other) and, when the Android source is reachable from the test environment (true in this
monorepo), a second test parses AuditLogger.kt directly and asserts THIS file matches it, so the
mirror itself cannot silently go stale the way the hand-typed guess it replaces did.

`REFERRAL_STATUS_CHANGED` / "referral_status_changed" is included even though it is dormant on
the device today (the Android session found `ReferralDao.updateStatus` has no live caller yet).
Operator decision: the accepted set is a superset that never has to shrink, so accepting a
not-yet-emitted value now is cheap, and accepting it late would require a coordinated field
migration once a caller does exist.
"""

from __future__ import annotations

DEVICE_AUDIT_ACTIONS: frozenset[str] = frozenset(
    {
        "abha_login_verified",
        "abha_profile_created",
        "ailment_captured",
        "ailment_deleted",
        "allergy_added",
        "attachment_added",
        "audio_captured",
        "case_queued_for_sync",
        "case_sent_to_doctor",
        "consent_recorded",
        "consultation_locked",
        "consultation_saved",
        "diagnosis_feedback_recorded",
        "emergency_override",
        "encounter_resumed",
        "encounter_started",
        "evaluate_response_failed",
        "evaluate_response_received",
        "family_history_added",
        "kernel_assessment_acknowledged",
        # Emitted when /api/v1/assess answers 200 with an empty differential_diagnosis: the
        # device routes the case to InferenceSource.UNAVAILABLE and records this so field
        # analysis can separate an unreachable kernel from one returning empty differentials.
        # Added with the device-side empty-200 fabrication fix, same change as the Kotlin enum
        # value, because a device action this set does not accept is a permanent silent sync
        # rejection of a row the device will keep re-sending.
        "kernel_empty_differential",
        "kernel_response_received",
        "medical_history_item_added",
        "medication_added",
        "patient_registered",
        "referral_created",
        "referral_status_changed",
        "report_exported",
        "social_history_saved",
        "transcription_completed",
        "vitals_recorded",
        # ASR track (asr-field-audit-memo.md B.4), one per confirmation-gate state. Not emitted
        # by the device yet; PR 3 wires the confirmation gate. Added with the Kotlin enum values
        # in the same commit, same reasoning as referral_status_changed above: an accepted set
        # missing a value the device later starts sending is a silent, permanent sync rejection.
        "voice_field_confirmed",
        "voice_field_edited",
        "voice_field_rejected",
        "voice_field_suggested",
    }
)
