"""Clinical tables: the 20 Room entities mirrored, plus the operational tables.

Twenty tables carry the same names and the snake_case form of the same fields the Room schema
uses, so a sync push is a dumb row operation rather than a translation layer. Three more
(sync_batches, sync_log, kernel_call_log) exist only on the server and are populated by Phases 3
and 4; creating them now keeps those phases route work rather than migration work.

Two deliberate divergences from the device schema, both recorded in backend-prd.md section 4:

- Foreign keys are real here. Room has none, for sound offline reasons that do not apply to the
  durable copy of a clinical record. The cost is that sync push must apply records in dependency
  order (api-contract.md section 6.1).
- Patient identity columns are pgcrypto ciphertext (bytea), with HMAC blind indexes beside them
  for exact-match lookup. pgcrypto itself is already installed by migration 0001.

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-17
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.db.types
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "abha_profiles",
        sa.Column("abha_id", sa.String(length=14), nullable=False),
        sa.Column("abha_address", sa.String(length=255), nullable=True),
        sa.Column("name", app.db.types.EncryptedText(), nullable=False),
        sa.Column("mobile_number", app.db.types.EncryptedText(), nullable=True),
        sa.Column("email_address", app.db.types.EncryptedText(), nullable=True),
        sa.Column("mobile_blind_idx", sa.String(length=32), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("gender", sa.String(length=20), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("district", sa.String(length=120), nullable=True),
        sa.Column("state", sa.String(length=120), nullable=True),
        sa.Column("pincode", sa.String(length=6), nullable=True),
        sa.Column("photo_url_mock", sa.Text(), nullable=True),
        sa.Column("kyc_verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("facility_id", sa.String(length=32), nullable=False),
        sa.Column("server_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_state", sa.String(length=20), server_default="RECEIVED", nullable=False),
        sa.CheckConstraint(
            "abha_id ~ '^[0-9]{14}$'", name=op.f("ck_abha_profiles_ck_abha_profiles_id_format")
        ),
        sa.CheckConstraint(
            "sync_state IN ('RECEIVED', 'CONFLICT')",
            name=op.f("ck_abha_profiles_abha_profiles_sync_state"),
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
            name=op.f("fk_abha_profiles_facility_id_facilities"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("abha_id", name=op.f("pk_abha_profiles")),
    )
    op.create_index(
        op.f("ix_abha_profiles_facility_id"), "abha_profiles", ["facility_id"], unique=False
    )
    op.create_index(
        "ix_abha_profiles_mobile_blind_idx", "abha_profiles", ["mobile_blind_idx"], unique=False
    )
    op.create_index(
        op.f("ix_abha_profiles_sync_state"), "abha_profiles", ["sync_state"], unique=False
    )
    op.create_table(
        "doctors",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("specialty", sa.String(length=120), nullable=False),
        sa.Column("available", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("facility_name", sa.String(length=200), nullable=True),
        sa.Column("registration_number", sa.String(length=60), nullable=True),
        sa.Column("facility_id", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
            name=op.f("fk_doctors_facility_id_facilities"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_doctors")),
    )
    op.create_index(op.f("ix_doctors_facility_id"), "doctors", ["facility_id"], unique=False)
    op.create_index("ix_doctors_specialty", "doctors", ["specialty"], unique=False)
    op.create_table(
        "kernel_call_log",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("worker_id", sa.String(length=16), nullable=False),
        sa.Column("facility_id", sa.String(length=32), nullable=False),
        sa.Column("case_token", sa.String(length=36), nullable=False),
        sa.Column("endpoint", sa.String(length=60), nullable=False),
        sa.Column("input_sha256", sa.String(length=64), nullable=False),
        sa.Column("output_sha256", sa.String(length=64), nullable=True),
        sa.Column("model_version", sa.String(length=80), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
            name=op.f("fk_kernel_call_log_facility_id_facilities"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kernel_call_log")),
    )
    op.create_index(
        "ix_kernel_call_log_case_token", "kernel_call_log", ["case_token"], unique=False
    )
    op.create_index(
        "ix_kernel_call_log_facility_created",
        "kernel_call_log",
        ["facility_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_kernel_call_log_request_id", "kernel_call_log", ["request_id"], unique=False
    )
    op.create_table(
        "patients",
        sa.Column("id", sa.String(length=12), nullable=False),
        sa.Column("full_name", app.db.types.EncryptedText(), nullable=False),
        sa.Column("guardian_or_spouse_name", app.db.types.EncryptedText(), nullable=True),
        sa.Column("mobile_number", app.db.types.EncryptedText(), nullable=True),
        sa.Column("aadhaar_number", app.db.types.EncryptedText(), nullable=True),
        sa.Column("emergency_contact", app.db.types.EncryptedText(), nullable=True),
        sa.Column("name_blind_idx", sa.String(length=32), nullable=True),
        sa.Column("aadhaar_blind_idx", sa.String(length=32), nullable=True),
        sa.Column("mobile_blind_idx", sa.String(length=32), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("biological_sex", sa.String(length=20), nullable=False),
        sa.Column("guardian_relation", sa.String(length=50), nullable=True),
        sa.Column("village", sa.String(length=120), nullable=True),
        sa.Column("block", sa.String(length=120), nullable=True),
        sa.Column("district", sa.String(length=120), nullable=True),
        sa.Column("state", sa.String(length=120), nullable=True),
        sa.Column("pincode", sa.String(length=6), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("marital_status", sa.String(length=50), nullable=True),
        sa.Column("blood_group", sa.String(length=10), nullable=True),
        sa.Column("primary_care_clinic_name", sa.String(length=200), nullable=True),
        sa.Column("referring_physician_name", sa.String(length=200), nullable=True),
        sa.Column("abha_number", sa.String(length=14), nullable=True),
        sa.Column("abha_address", sa.String(length=255), nullable=True),
        sa.Column("abha_status", sa.String(length=20), nullable=True),
        sa.Column("kyc_status", sa.String(length=20), nullable=True),
        sa.Column("verification_source", sa.String(length=40), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("facility_id", sa.String(length=32), nullable=False),
        sa.Column("server_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_state", sa.String(length=20), server_default="RECEIVED", nullable=False),
        sa.CheckConstraint(
            "abha_number IS NULL OR abha_number ~ '^[0-9]{14}$'",
            name=op.f("ck_patients_ck_patients_abha_format"),
        ),
        sa.CheckConstraint(
            "id ~ '^[A-Za-z0-9]{10,12}$'", name=op.f("ck_patients_ck_patients_id_format")
        ),
        sa.CheckConstraint(
            "sync_state IN ('RECEIVED', 'CONFLICT')", name=op.f("ck_patients_patients_sync_state")
        ),
        sa.CheckConstraint(
            "age IS NULL OR (age >= 0 AND age <= 130)",
            name=op.f("ck_patients_ck_patients_age_range"),
        ),
        sa.CheckConstraint(
            "mobile_blind_idx IS NOT NULL OR village IS NOT NULL OR district IS NOT NULL",
            name=op.f("ck_patients_ck_patients_contact_method"),
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
            name=op.f("fk_patients_facility_id_facilities"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_patients")),
    )
    op.create_index(
        "ix_patients_aadhaar_blind_idx", "patients", ["aadhaar_blind_idx"], unique=False
    )
    op.create_index("ix_patients_abha_number", "patients", ["abha_number"], unique=True)
    op.create_index(op.f("ix_patients_facility_id"), "patients", ["facility_id"], unique=False)
    op.create_index(
        "ix_patients_facility_updated", "patients", ["facility_id", "updated_at"], unique=False
    )
    op.create_index("ix_patients_mobile_blind_idx", "patients", ["mobile_blind_idx"], unique=False)
    op.create_index("ix_patients_name_blind_idx", "patients", ["name_blind_idx"], unique=False)
    op.create_index(op.f("ix_patients_sync_state"), "patients", ["sync_state"], unique=False)
    op.create_table(
        "sync_batches",
        sa.Column("batch_id", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=64), nullable=False),
        sa.Column("worker_id", sa.String(length=16), nullable=False),
        sa.Column("facility_id", sa.String(length=32), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("record_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("applied", sa.Integer(), server_default="0", nullable=False),
        sa.Column("stale", sa.Integer(), server_default="0", nullable=False),
        sa.Column("conflicted", sa.Integer(), server_default="0", nullable=False),
        sa.Column("rejected", sa.Integer(), server_default="0", nullable=False),
        sa.Column("response_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
            name=op.f("fk_sync_batches_facility_id_facilities"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("batch_id", name=op.f("pk_sync_batches")),
    )
    op.create_index("ix_sync_batches_device_id", "sync_batches", ["device_id"], unique=False)
    op.create_index(
        "ix_sync_batches_facility_received",
        "sync_batches",
        ["facility_id", "received_at"],
        unique=False,
    )
    op.create_table(
        "allergies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=12), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("allergen", sa.String(length=200), nullable=False),
        sa.Column("reaction_type", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("facility_id", sa.String(length=32), nullable=False),
        sa.Column("server_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_state", sa.String(length=20), server_default="RECEIVED", nullable=False),
        sa.CheckConstraint(
            "category IN ('DRUG', 'FOOD', 'ENVIRONMENTAL')",
            name=op.f("ck_allergies_ck_allergies_category"),
        ),
        sa.CheckConstraint(
            "sync_state IN ('RECEIVED', 'CONFLICT')", name=op.f("ck_allergies_allergies_sync_state")
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
            name=op.f("fk_allergies_facility_id_facilities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_allergies_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_allergies")),
    )
    op.create_index(op.f("ix_allergies_facility_id"), "allergies", ["facility_id"], unique=False)
    op.create_index("ix_allergies_patient_id", "allergies", ["patient_id"], unique=False)
    op.create_index(op.f("ix_allergies_sync_state"), "allergies", ["sync_state"], unique=False)
    op.create_table(
        "encounters",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=12), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("follow_up_of_encounter_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("facility_id", sa.String(length=32), nullable=False),
        sa.Column("server_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_state", sa.String(length=20), server_default="RECEIVED", nullable=False),
        sa.CheckConstraint(
            "sync_state IN ('RECEIVED', 'CONFLICT')",
            name=op.f("ck_encounters_encounters_sync_state"),
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
            name=op.f("fk_encounters_facility_id_facilities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["follow_up_of_encounter_id"],
            ["encounters.id"],
            name=op.f("fk_encounters_follow_up_of_encounter_id_encounters"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_encounters_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_encounters")),
    )
    op.create_index(op.f("ix_encounters_facility_id"), "encounters", ["facility_id"], unique=False)
    op.create_index(
        "ix_encounters_facility_started", "encounters", ["facility_id", "started_at"], unique=False
    )
    op.create_index("ix_encounters_patient_id", "encounters", ["patient_id"], unique=False)
    op.create_index(op.f("ix_encounters_sync_state"), "encounters", ["sync_state"], unique=False)
    op.create_table(
        "family_history_entries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=12), nullable=False),
        sa.Column("condition", sa.String(length=200), nullable=False),
        sa.Column("relation", sa.String(length=60), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("facility_id", sa.String(length=32), nullable=False),
        sa.Column("server_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_state", sa.String(length=20), server_default="RECEIVED", nullable=False),
        sa.CheckConstraint(
            "sync_state IN ('RECEIVED', 'CONFLICT')",
            name=op.f("ck_family_history_entries_family_history_entries_sync_state"),
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
            name=op.f("fk_family_history_entries_facility_id_facilities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_family_history_entries_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_family_history_entries")),
    )
    op.create_index(
        op.f("ix_family_history_entries_facility_id"),
        "family_history_entries",
        ["facility_id"],
        unique=False,
    )
    op.create_index(
        "ix_family_history_entries_patient_id",
        "family_history_entries",
        ["patient_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_family_history_entries_sync_state"),
        "family_history_entries",
        ["sync_state"],
        unique=False,
    )
    op.create_table(
        "medical_history_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=12), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("year_or_date", sa.String(length=40), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("facility_id", sa.String(length=32), nullable=False),
        sa.Column("server_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_state", sa.String(length=20), server_default="RECEIVED", nullable=False),
        sa.CheckConstraint(
            "category IN ('CHRONIC_CONDITION', 'SURGERY', 'HOSPITALIZATION')",
            name=op.f("ck_medical_history_items_ck_medical_history_items_category"),
        ),
        sa.CheckConstraint(
            "sync_state IN ('RECEIVED', 'CONFLICT')",
            name=op.f("ck_medical_history_items_medical_history_items_sync_state"),
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
            name=op.f("fk_medical_history_items_facility_id_facilities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_medical_history_items_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_medical_history_items")),
    )
    op.create_index(
        op.f("ix_medical_history_items_facility_id"),
        "medical_history_items",
        ["facility_id"],
        unique=False,
    )
    op.create_index(
        "ix_medical_history_items_patient_id", "medical_history_items", ["patient_id"], unique=False
    )
    op.create_index(
        op.f("ix_medical_history_items_sync_state"),
        "medical_history_items",
        ["sync_state"],
        unique=False,
    )
    op.create_table(
        "social_histories",
        sa.Column("patient_id", sa.String(length=12), nullable=False),
        sa.Column("occupation", sa.String(length=120), nullable=True),
        sa.Column("tobacco_use", sa.String(length=120), nullable=True),
        sa.Column("alcohol_use", sa.String(length=120), nullable=True),
        sa.Column("recreational_drug_use", sa.String(length=120), nullable=True),
        sa.Column("environmental_exposure", sa.Text(), nullable=True),
        sa.Column("recent_travel", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("facility_id", sa.String(length=32), nullable=False),
        sa.Column("server_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_state", sa.String(length=20), server_default="RECEIVED", nullable=False),
        sa.CheckConstraint(
            "sync_state IN ('RECEIVED', 'CONFLICT')",
            name=op.f("ck_social_histories_social_histories_sync_state"),
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
            name=op.f("fk_social_histories_facility_id_facilities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_social_histories_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("patient_id", name=op.f("pk_social_histories")),
    )
    op.create_index(
        op.f("ix_social_histories_facility_id"), "social_histories", ["facility_id"], unique=False
    )
    op.create_index(
        op.f("ix_social_histories_sync_state"), "social_histories", ["sync_state"], unique=False
    )
    op.create_table(
        "sync_log",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("batch_id", sa.String(length=36), nullable=False),
        sa.Column("table_name", sa.String(length=60), nullable=False),
        sa.Column("record_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("server_version", sa.Integer(), nullable=True),
        sa.Column(
            "applied_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["sync_batches.batch_id"],
            name=op.f("fk_sync_log_batch_id_sync_batches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_log")),
    )
    op.create_index("ix_sync_log_batch_id", "sync_log", ["batch_id"], unique=False)
    op.create_index(
        "ix_sync_log_table_record", "sync_log", ["table_name", "record_id"], unique=False
    )
    op.create_table(
        "ailments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=12), nullable=False),
        sa.Column("encounter_id", sa.String(length=36), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("measurement_type", sa.String(length=20), nullable=False),
        sa.Column("visibility", sa.String(length=10), nullable=False),
        sa.Column("measured_value", sa.Float(), nullable=True),
        sa.Column("measured_unit", sa.String(length=20), nullable=True),
        sa.Column("severity", sa.Integer(), nullable=True),
        sa.Column("onset", sa.String(length=120), nullable=True),
        sa.Column("duration", sa.String(length=120), nullable=True),
        sa.Column("qualifiers", sa.Text(), nullable=True),
        sa.Column("captured_at_offline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("synced_to_cloud_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("facility_id", sa.String(length=32), nullable=False),
        sa.Column("server_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_state", sa.String(length=20), server_default="RECEIVED", nullable=False),
        sa.CheckConstraint(
            "measurement_type IN ('MEASURABLE', 'NON_MEASURABLE')",
            name=op.f("ck_ailments_ck_ailments_measurement_type"),
        ),
        sa.CheckConstraint(
            "sync_state IN ('RECEIVED', 'CONFLICT')", name=op.f("ck_ailments_ailments_sync_state")
        ),
        sa.CheckConstraint(
            "visibility IN ('PUBLIC', 'PRIVATE')", name=op.f("ck_ailments_ck_ailments_visibility")
        ),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounters.id"],
            name=op.f("fk_ailments_encounter_id_encounters"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
            name=op.f("fk_ailments_facility_id_facilities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_ailments_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ailments")),
    )
    op.create_index("ix_ailments_encounter_id", "ailments", ["encounter_id"], unique=False)
    op.create_index(op.f("ix_ailments_facility_id"), "ailments", ["facility_id"], unique=False)
    op.create_index("ix_ailments_patient_id", "ailments", ["patient_id"], unique=False)
    op.create_index(op.f("ix_ailments_sync_state"), "ailments", ["sync_state"], unique=False)
    op.create_table(
        "case_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=12), nullable=False),
        sa.Column("encounter_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("assigned_doctor_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("facility_id", sa.String(length=32), nullable=False),
        sa.Column("server_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_state", sa.String(length=20), server_default="RECEIVED", nullable=False),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'SAVED_LOCALLY', 'PENDING_SYNC', 'SENT_TO_DOCTOR', 'PRESCRIPTION_RECEIVED', 'ABANDONED')",
            name=op.f("ck_case_records_ck_case_records_status"),
        ),
        sa.CheckConstraint(
            "sync_state IN ('RECEIVED', 'CONFLICT')",
            name=op.f("ck_case_records_case_records_sync_state"),
        ),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounters.id"],
            name=op.f("fk_case_records_encounter_id_encounters"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
            name=op.f("fk_case_records_facility_id_facilities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_case_records_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_case_records")),
    )
    op.create_index(
        op.f("ix_case_records_assigned_doctor_id"),
        "case_records",
        ["assigned_doctor_id"],
        unique=False,
    )
    op.create_index("ix_case_records_encounter_id", "case_records", ["encounter_id"], unique=False)
    op.create_index(
        op.f("ix_case_records_facility_id"), "case_records", ["facility_id"], unique=False
    )
    op.create_index(
        "ix_case_records_facility_status", "case_records", ["facility_id", "status"], unique=False
    )
    op.create_index("ix_case_records_patient_id", "case_records", ["patient_id"], unique=False)
    op.create_index(
        op.f("ix_case_records_sync_state"), "case_records", ["sync_state"], unique=False
    )
    op.create_table(
        "consultations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=12), nullable=False),
        sa.Column("encounter_id", sa.String(length=36), nullable=False),
        sa.Column("chief_complaint", sa.Text(), nullable=False),
        sa.Column("onset", sa.String(length=120), nullable=True),
        sa.Column("duration_bucket", sa.String(length=40), nullable=True),
        sa.Column("severity_score", sa.Integer(), nullable=True),
        sa.Column("aggravating_factors", sa.Text(), nullable=True),
        sa.Column("relieving_factors", sa.Text(), nullable=True),
        sa.Column("impact_on_daily_activities", sa.Text(), nullable=True),
        sa.Column("relevant_history", sa.Text(), nullable=True),
        sa.Column("transcription", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("facility_id", sa.String(length=32), nullable=False),
        sa.Column("server_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_state", sa.String(length=20), server_default="RECEIVED", nullable=False),
        sa.CheckConstraint(
            "sync_state IN ('RECEIVED', 'CONFLICT')",
            name=op.f("ck_consultations_consultations_sync_state"),
        ),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounters.id"],
            name=op.f("fk_consultations_encounter_id_encounters"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
            name=op.f("fk_consultations_facility_id_facilities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_consultations_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consultations")),
    )
    op.create_index(
        "ix_consultations_encounter_id", "consultations", ["encounter_id"], unique=False
    )
    op.create_index(
        op.f("ix_consultations_facility_id"), "consultations", ["facility_id"], unique=False
    )
    op.create_index("ix_consultations_patient_id", "consultations", ["patient_id"], unique=False)
    op.create_index(
        op.f("ix_consultations_sync_state"), "consultations", ["sync_state"], unique=False
    )
    op.create_table(
        "medication_entries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=12), nullable=False),
        sa.Column("encounter_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("dosage", sa.String(length=120), nullable=True),
        sa.Column("frequency", sa.String(length=120), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("facility_id", sa.String(length=32), nullable=False),
        sa.Column("server_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_state", sa.String(length=20), server_default="RECEIVED", nullable=False),
        sa.CheckConstraint(
            "kind IN ('MEDICATION', 'SUPPLEMENT')",
            name=op.f("ck_medication_entries_ck_medication_entries_kind"),
        ),
        sa.CheckConstraint(
            "sync_state IN ('RECEIVED', 'CONFLICT')",
            name=op.f("ck_medication_entries_medication_entries_sync_state"),
        ),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounters.id"],
            name=op.f("fk_medication_entries_encounter_id_encounters"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
            name=op.f("fk_medication_entries_facility_id_facilities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_medication_entries_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_medication_entries")),
    )
    op.create_index(
        op.f("ix_medication_entries_facility_id"),
        "medication_entries",
        ["facility_id"],
        unique=False,
    )
    op.create_index(
        "ix_medication_entries_patient_id", "medication_entries", ["patient_id"], unique=False
    )
    op.create_index(
        op.f("ix_medication_entries_sync_state"), "medication_entries", ["sync_state"], unique=False
    )
    op.create_table(
        "observations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=12), nullable=False),
        sa.Column("encounter_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("value_numeric", sa.Float(), nullable=True),
        sa.Column("value_text", sa.Text(), nullable=True),
        sa.Column("unit", sa.String(length=20), nullable=True),
        sa.Column("device_id", sa.String(length=64), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("capture_method", sa.String(length=30), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("synced_to_cloud_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("facility_id", sa.String(length=32), nullable=False),
        sa.Column("server_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_state", sa.String(length=20), server_default="RECEIVED", nullable=False),
        sa.CheckConstraint(
            "capture_method IN ('MANUAL_CUFF', 'DIGITAL_MONITOR', 'PULSE_OXIMETER', 'THERMOMETER', 'OTHER')",
            name=op.f("ck_observations_ck_observations_capture_method"),
        ),
        sa.CheckConstraint(
            "source IN ('MANUAL', 'DEVICE')", name=op.f("ck_observations_ck_observations_source")
        ),
        sa.CheckConstraint(
            "sync_state IN ('RECEIVED', 'CONFLICT')",
            name=op.f("ck_observations_observations_sync_state"),
        ),
        sa.CheckConstraint(
            "type IN ('PULSE', 'BP_SYSTOLIC', 'BP_DIASTOLIC', 'SPO2', 'TEMPERATURE', 'RESPIRATORY_RATE', 'WEIGHT', 'HEIGHT', 'BMI', 'BLOOD_GLUCOSE', 'PAIN_SCORE', 'URINALYSIS')",
            name=op.f("ck_observations_ck_observations_type"),
        ),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounters.id"],
            name=op.f("fk_observations_encounter_id_encounters"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
            name=op.f("fk_observations_facility_id_facilities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_observations_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observations")),
    )
    op.create_index("ix_observations_encounter_id", "observations", ["encounter_id"], unique=False)
    op.create_index(
        op.f("ix_observations_facility_id"), "observations", ["facility_id"], unique=False
    )
    op.create_index("ix_observations_patient_id", "observations", ["patient_id"], unique=False)
    op.create_index(
        op.f("ix_observations_sync_state"), "observations", ["sync_state"], unique=False
    )
    op.create_table(
        "attachments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("consultation_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("local_uri", sa.Text(), nullable=False),
        sa.Column(
            "blob_status", sa.String(length=20), server_default="NOT_UPLOADED", nullable=False
        ),
        sa.Column("object_key", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("facility_id", sa.String(length=32), nullable=False),
        sa.Column("server_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_state", sa.String(length=20), server_default="RECEIVED", nullable=False),
        sa.CheckConstraint(
            "blob_status IN ('NOT_UPLOADED', 'UPLOADED')",
            name=op.f("ck_attachments_ck_attachments_blob_status"),
        ),
        sa.CheckConstraint(
            "sync_state IN ('RECEIVED', 'CONFLICT')",
            name=op.f("ck_attachments_attachments_sync_state"),
        ),
        sa.CheckConstraint(
            "type IN ('IMAGE', 'VIDEO', 'AUDIO', 'AFFECTED_AREA_PHOTO')",
            name=op.f("ck_attachments_ck_attachments_type"),
        ),
        sa.ForeignKeyConstraint(
            ["consultation_id"],
            ["consultations.id"],
            name=op.f("fk_attachments_consultation_id_consultations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
            name=op.f("fk_attachments_facility_id_facilities"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachments")),
    )
    op.create_index(
        "ix_attachments_consultation_id", "attachments", ["consultation_id"], unique=False
    )
    op.create_index(
        op.f("ix_attachments_facility_id"), "attachments", ["facility_id"], unique=False
    )
    op.create_index(op.f("ix_attachments_sync_state"), "attachments", ["sync_state"], unique=False)
    op.create_table(
        "diagnosis_feedback",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_record_id", sa.String(length=36), nullable=False),
        sa.Column("icd_candidate", sa.String(length=20), nullable=False),
        sa.Column("physician_decision", sa.String(length=10), nullable=False),
        sa.Column("physician_final_diagnosis", sa.String(length=20), nullable=True),
        sa.Column("clinical_note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("facility_id", sa.String(length=32), nullable=False),
        sa.Column("server_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_state", sa.String(length=20), server_default="RECEIVED", nullable=False),
        sa.CheckConstraint(
            "physician_decision IN ('AGREE', 'MODIFY', 'REJECT')",
            name=op.f("ck_diagnosis_feedback_ck_diagnosis_feedback_decision"),
        ),
        sa.CheckConstraint(
            "sync_state IN ('RECEIVED', 'CONFLICT')",
            name=op.f("ck_diagnosis_feedback_diagnosis_feedback_sync_state"),
        ),
        sa.ForeignKeyConstraint(
            ["case_record_id"],
            ["case_records.id"],
            name=op.f("fk_diagnosis_feedback_case_record_id_case_records"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
            name=op.f("fk_diagnosis_feedback_facility_id_facilities"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_diagnosis_feedback")),
    )
    op.create_index(
        "ix_diagnosis_feedback_case_record_id",
        "diagnosis_feedback",
        ["case_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_diagnosis_feedback_facility_id"),
        "diagnosis_feedback",
        ["facility_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_diagnosis_feedback_sync_state"), "diagnosis_feedback", ["sync_state"], unique=False
    )
    op.create_table(
        "evaluate_reports",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_record_id", sa.String(length=36), nullable=False),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("inference_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("inference_ended_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("facility_id", sa.String(length=32), nullable=False),
        sa.Column("server_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_state", sa.String(length=20), server_default="RECEIVED", nullable=False),
        sa.CheckConstraint(
            "sync_state IN ('RECEIVED', 'CONFLICT')",
            name=op.f("ck_evaluate_reports_evaluate_reports_sync_state"),
        ),
        sa.ForeignKeyConstraint(
            ["case_record_id"],
            ["case_records.id"],
            name=op.f("fk_evaluate_reports_case_record_id_case_records"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
            name=op.f("fk_evaluate_reports_facility_id_facilities"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluate_reports")),
    )
    op.create_index(
        "ix_evaluate_reports_case_record_id", "evaluate_reports", ["case_record_id"], unique=False
    )
    op.create_index(
        op.f("ix_evaluate_reports_facility_id"), "evaluate_reports", ["facility_id"], unique=False
    )
    op.create_index(
        op.f("ix_evaluate_reports_sync_state"), "evaluate_reports", ["sync_state"], unique=False
    )
    op.create_table(
        "kernel_reports",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_record_id", sa.String(length=36), nullable=False),
        sa.Column("predicted_condition", sa.Text(), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("differentials", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("reasoning_summary", sa.Text(), nullable=False),
        sa.Column("evidence_for", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("evidence_against", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("model_version", sa.String(length=80), nullable=False),
        sa.Column("icd_code", sa.String(length=20), nullable=True),
        sa.Column("device_id", sa.String(length=64), nullable=False),
        sa.Column("software_version", sa.String(length=40), nullable=False),
        sa.Column("data_quality_score", sa.Float(), nullable=True),
        sa.Column("uncertainty_score", sa.Float(), nullable=True),
        sa.Column("risk_category", sa.String(length=20), nullable=False),
        sa.Column("urgency_level", sa.String(length=20), nullable=False),
        sa.Column("inference_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("inference_ended_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("required_human_verification", sa.Boolean(), nullable=False),
        sa.Column("inference_source", sa.String(length=20), nullable=False),
        sa.Column("facility_id", sa.String(length=32), nullable=False),
        sa.Column("server_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_state", sa.String(length=20), server_default="RECEIVED", nullable=False),
        sa.CheckConstraint(
            "inference_source IN ('REAL_INFERENCE', 'MOCK_FALLBACK')",
            name=op.f("ck_kernel_reports_ck_kernel_reports_inference_source"),
        ),
        sa.CheckConstraint(
            "risk_category IN ('LOW', 'MODERATE', 'HIGH', 'CRITICAL')",
            name=op.f("ck_kernel_reports_ck_kernel_reports_risk_category"),
        ),
        sa.CheckConstraint(
            "sync_state IN ('RECEIVED', 'CONFLICT')",
            name=op.f("ck_kernel_reports_kernel_reports_sync_state"),
        ),
        sa.CheckConstraint(
            "urgency_level IN ('ROUTINE', 'URGENT', 'EMERGENCY')",
            name=op.f("ck_kernel_reports_ck_kernel_reports_urgency_level"),
        ),
        sa.ForeignKeyConstraint(
            ["case_record_id"],
            ["case_records.id"],
            name=op.f("fk_kernel_reports_case_record_id_case_records"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
            name=op.f("fk_kernel_reports_facility_id_facilities"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kernel_reports")),
    )
    op.create_index(
        "ix_kernel_reports_case_record_id", "kernel_reports", ["case_record_id"], unique=False
    )
    op.create_index(
        op.f("ix_kernel_reports_facility_id"), "kernel_reports", ["facility_id"], unique=False
    )
    op.create_index(
        "ix_kernel_reports_facility_source",
        "kernel_reports",
        ["facility_id", "inference_source"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kernel_reports_sync_state"), "kernel_reports", ["sync_state"], unique=False
    )
    op.create_table(
        "prescriptions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=12), nullable=False),
        sa.Column("encounter_id", sa.String(length=36), nullable=False),
        sa.Column("case_record_id", sa.String(length=36), nullable=False),
        sa.Column("doctor_id", sa.String(length=36), nullable=False),
        sa.Column("diagnosis", sa.Text(), nullable=False),
        sa.Column("kernel_decision", sa.String(length=10), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("facility_id", sa.String(length=32), nullable=False),
        sa.Column("server_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_state", sa.String(length=20), server_default="RECEIVED", nullable=False),
        sa.CheckConstraint(
            "kernel_decision IN ('AGREE', 'MODIFY', 'REJECT')",
            name=op.f("ck_prescriptions_ck_prescriptions_kernel_decision"),
        ),
        sa.CheckConstraint(
            "sync_state IN ('RECEIVED', 'CONFLICT')",
            name=op.f("ck_prescriptions_prescriptions_sync_state"),
        ),
        sa.ForeignKeyConstraint(
            ["case_record_id"],
            ["case_records.id"],
            name=op.f("fk_prescriptions_case_record_id_case_records"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounters.id"],
            name=op.f("fk_prescriptions_encounter_id_encounters"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
            name=op.f("fk_prescriptions_facility_id_facilities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_prescriptions_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prescriptions")),
    )
    op.create_index(
        "ix_prescriptions_case_record_id", "prescriptions", ["case_record_id"], unique=False
    )
    op.create_index(
        op.f("ix_prescriptions_doctor_id"), "prescriptions", ["doctor_id"], unique=False
    )
    op.create_index(
        op.f("ix_prescriptions_facility_id"), "prescriptions", ["facility_id"], unique=False
    )
    op.create_index("ix_prescriptions_patient_id", "prescriptions", ["patient_id"], unique=False)
    op.create_index(
        op.f("ix_prescriptions_sync_state"), "prescriptions", ["sync_state"], unique=False
    )
    op.create_table(
        "referrals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_uid", sa.String(length=12), nullable=False),
        sa.Column("case_record_id", sa.String(length=36), nullable=False),
        sa.Column("urgency_level", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("sending_phc_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("facility_id", sa.String(length=32), nullable=False),
        sa.Column("server_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_state", sa.String(length=20), server_default="RECEIVED", nullable=False),
        sa.CheckConstraint(
            "status IN ('QUEUED', 'SENT', 'ACKNOWLEDGED', 'CANCELLED')",
            name=op.f("ck_referrals_ck_referrals_status"),
        ),
        sa.CheckConstraint(
            "sync_state IN ('RECEIVED', 'CONFLICT')", name=op.f("ck_referrals_referrals_sync_state")
        ),
        sa.CheckConstraint(
            "urgency_level IN ('ROUTINE', 'URGENT', 'EMERGENCY')",
            name=op.f("ck_referrals_ck_referrals_urgency_level"),
        ),
        sa.ForeignKeyConstraint(
            ["case_record_id"],
            ["case_records.id"],
            name=op.f("fk_referrals_case_record_id_case_records"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
            name=op.f("fk_referrals_facility_id_facilities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_uid"],
            ["patients.id"],
            name=op.f("fk_referrals_patient_uid_patients"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_referrals")),
    )
    op.create_index("ix_referrals_case_record_id", "referrals", ["case_record_id"], unique=False)
    op.create_index(op.f("ix_referrals_facility_id"), "referrals", ["facility_id"], unique=False)
    op.create_index("ix_referrals_patient_uid", "referrals", ["patient_uid"], unique=False)
    op.create_index(op.f("ix_referrals_sync_state"), "referrals", ["sync_state"], unique=False)
    op.create_table(
        "medication_lines",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("prescription_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("generic_name", sa.String(length=200), nullable=False),
        sa.Column("brand_name", sa.String(length=200), nullable=True),
        sa.Column("strength", sa.String(length=80), nullable=False),
        sa.Column("dosage", sa.String(length=120), nullable=False),
        sa.Column("frequency", sa.String(length=120), nullable=False),
        sa.Column("route", sa.String(length=60), nullable=False),
        sa.Column("duration", sa.String(length=80), nullable=False),
        sa.Column("quantity", sa.String(length=60), nullable=False),
        sa.Column("food_relation", sa.String(length=80), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("facility_id", sa.String(length=32), nullable=False),
        sa.Column("server_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_state", sa.String(length=20), server_default="RECEIVED", nullable=False),
        sa.CheckConstraint(
            "sync_state IN ('RECEIVED', 'CONFLICT')",
            name=op.f("ck_medication_lines_medication_lines_sync_state"),
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
            name=op.f("fk_medication_lines_facility_id_facilities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["prescription_id"],
            ["prescriptions.id"],
            name=op.f("fk_medication_lines_prescription_id_prescriptions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_medication_lines")),
        sa.UniqueConstraint("prescription_id", "position", name="uq_medication_lines_position"),
    )
    op.create_index(
        op.f("ix_medication_lines_facility_id"), "medication_lines", ["facility_id"], unique=False
    )
    op.create_index(
        "ix_medication_lines_prescription_id", "medication_lines", ["prescription_id"], unique=False
    )
    op.create_index(
        op.f("ix_medication_lines_sync_state"), "medication_lines", ["sync_state"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_medication_lines_sync_state"), table_name="medication_lines")
    op.drop_index("ix_medication_lines_prescription_id", table_name="medication_lines")
    op.drop_index(op.f("ix_medication_lines_facility_id"), table_name="medication_lines")
    op.drop_table("medication_lines")
    op.drop_index(op.f("ix_referrals_sync_state"), table_name="referrals")
    op.drop_index("ix_referrals_patient_uid", table_name="referrals")
    op.drop_index(op.f("ix_referrals_facility_id"), table_name="referrals")
    op.drop_index("ix_referrals_case_record_id", table_name="referrals")
    op.drop_table("referrals")
    op.drop_index(op.f("ix_prescriptions_sync_state"), table_name="prescriptions")
    op.drop_index("ix_prescriptions_patient_id", table_name="prescriptions")
    op.drop_index(op.f("ix_prescriptions_facility_id"), table_name="prescriptions")
    op.drop_index(op.f("ix_prescriptions_doctor_id"), table_name="prescriptions")
    op.drop_index("ix_prescriptions_case_record_id", table_name="prescriptions")
    op.drop_table("prescriptions")
    op.drop_index(op.f("ix_kernel_reports_sync_state"), table_name="kernel_reports")
    op.drop_index("ix_kernel_reports_facility_source", table_name="kernel_reports")
    op.drop_index(op.f("ix_kernel_reports_facility_id"), table_name="kernel_reports")
    op.drop_index("ix_kernel_reports_case_record_id", table_name="kernel_reports")
    op.drop_table("kernel_reports")
    op.drop_index(op.f("ix_evaluate_reports_sync_state"), table_name="evaluate_reports")
    op.drop_index(op.f("ix_evaluate_reports_facility_id"), table_name="evaluate_reports")
    op.drop_index("ix_evaluate_reports_case_record_id", table_name="evaluate_reports")
    op.drop_table("evaluate_reports")
    op.drop_index(op.f("ix_diagnosis_feedback_sync_state"), table_name="diagnosis_feedback")
    op.drop_index(op.f("ix_diagnosis_feedback_facility_id"), table_name="diagnosis_feedback")
    op.drop_index("ix_diagnosis_feedback_case_record_id", table_name="diagnosis_feedback")
    op.drop_table("diagnosis_feedback")
    op.drop_index(op.f("ix_attachments_sync_state"), table_name="attachments")
    op.drop_index(op.f("ix_attachments_facility_id"), table_name="attachments")
    op.drop_index("ix_attachments_consultation_id", table_name="attachments")
    op.drop_table("attachments")
    op.drop_index(op.f("ix_observations_sync_state"), table_name="observations")
    op.drop_index("ix_observations_patient_id", table_name="observations")
    op.drop_index(op.f("ix_observations_facility_id"), table_name="observations")
    op.drop_index("ix_observations_encounter_id", table_name="observations")
    op.drop_table("observations")
    op.drop_index(op.f("ix_medication_entries_sync_state"), table_name="medication_entries")
    op.drop_index("ix_medication_entries_patient_id", table_name="medication_entries")
    op.drop_index(op.f("ix_medication_entries_facility_id"), table_name="medication_entries")
    op.drop_table("medication_entries")
    op.drop_index(op.f("ix_consultations_sync_state"), table_name="consultations")
    op.drop_index("ix_consultations_patient_id", table_name="consultations")
    op.drop_index(op.f("ix_consultations_facility_id"), table_name="consultations")
    op.drop_index("ix_consultations_encounter_id", table_name="consultations")
    op.drop_table("consultations")
    op.drop_index(op.f("ix_case_records_sync_state"), table_name="case_records")
    op.drop_index("ix_case_records_patient_id", table_name="case_records")
    op.drop_index("ix_case_records_facility_status", table_name="case_records")
    op.drop_index(op.f("ix_case_records_facility_id"), table_name="case_records")
    op.drop_index("ix_case_records_encounter_id", table_name="case_records")
    op.drop_index(op.f("ix_case_records_assigned_doctor_id"), table_name="case_records")
    op.drop_table("case_records")
    op.drop_index(op.f("ix_ailments_sync_state"), table_name="ailments")
    op.drop_index("ix_ailments_patient_id", table_name="ailments")
    op.drop_index(op.f("ix_ailments_facility_id"), table_name="ailments")
    op.drop_index("ix_ailments_encounter_id", table_name="ailments")
    op.drop_table("ailments")
    op.drop_index("ix_sync_log_table_record", table_name="sync_log")
    op.drop_index("ix_sync_log_batch_id", table_name="sync_log")
    op.drop_table("sync_log")
    op.drop_index(op.f("ix_social_histories_sync_state"), table_name="social_histories")
    op.drop_index(op.f("ix_social_histories_facility_id"), table_name="social_histories")
    op.drop_table("social_histories")
    op.drop_index(op.f("ix_medical_history_items_sync_state"), table_name="medical_history_items")
    op.drop_index("ix_medical_history_items_patient_id", table_name="medical_history_items")
    op.drop_index(op.f("ix_medical_history_items_facility_id"), table_name="medical_history_items")
    op.drop_table("medical_history_items")
    op.drop_index(op.f("ix_family_history_entries_sync_state"), table_name="family_history_entries")
    op.drop_index("ix_family_history_entries_patient_id", table_name="family_history_entries")
    op.drop_index(
        op.f("ix_family_history_entries_facility_id"), table_name="family_history_entries"
    )
    op.drop_table("family_history_entries")
    op.drop_index(op.f("ix_encounters_sync_state"), table_name="encounters")
    op.drop_index("ix_encounters_patient_id", table_name="encounters")
    op.drop_index("ix_encounters_facility_started", table_name="encounters")
    op.drop_index(op.f("ix_encounters_facility_id"), table_name="encounters")
    op.drop_table("encounters")
    op.drop_index(op.f("ix_allergies_sync_state"), table_name="allergies")
    op.drop_index("ix_allergies_patient_id", table_name="allergies")
    op.drop_index(op.f("ix_allergies_facility_id"), table_name="allergies")
    op.drop_table("allergies")
    op.drop_index("ix_sync_batches_facility_received", table_name="sync_batches")
    op.drop_index("ix_sync_batches_device_id", table_name="sync_batches")
    op.drop_table("sync_batches")
    op.drop_index(op.f("ix_patients_sync_state"), table_name="patients")
    op.drop_index("ix_patients_name_blind_idx", table_name="patients")
    op.drop_index("ix_patients_mobile_blind_idx", table_name="patients")
    op.drop_index("ix_patients_facility_updated", table_name="patients")
    op.drop_index(op.f("ix_patients_facility_id"), table_name="patients")
    op.drop_index("ix_patients_abha_number", table_name="patients")
    op.drop_index("ix_patients_aadhaar_blind_idx", table_name="patients")
    op.drop_table("patients")
    op.drop_index("ix_kernel_call_log_request_id", table_name="kernel_call_log")
    op.drop_index("ix_kernel_call_log_facility_created", table_name="kernel_call_log")
    op.drop_index("ix_kernel_call_log_case_token", table_name="kernel_call_log")
    op.drop_table("kernel_call_log")
    op.drop_index("ix_doctors_specialty", table_name="doctors")
    op.drop_index(op.f("ix_doctors_facility_id"), table_name="doctors")
    op.drop_table("doctors")
    op.drop_index(op.f("ix_abha_profiles_sync_state"), table_name="abha_profiles")
    op.drop_index("ix_abha_profiles_mobile_blind_idx", table_name="abha_profiles")
    op.drop_index(op.f("ix_abha_profiles_facility_id"), table_name="abha_profiles")
    op.drop_table("abha_profiles")
    # ### end Alembic commands ###
