"""Extend kernel_call_log for the Phase 3 kernel proxy.

kernel_call_log was created in migration 0002 as a placeholder with the columns Phase 2 already
knew it needed (request_id, worker_id, facility_id, case_token, endpoint, the two hashes,
model_version, http_status, duration_ms, created_at). Phase 3 adds what only the proxy itself
can populate: the real case_record_id alongside the pseudonymous case_token (the whole reason
both are stored is so correlation is a lookup, not a scan, api-contract.md section 5.2), which
kernel deployment answered the call, a typed outcome and error_code distinguishing timeout from
unreachable from a kernel-side error from a rejected payload from the circuit breaker, and
completed_at alongside a rename of created_at to started_at so the row's own two timestamps read
as what they are: when the call began and when it finished.

created_at is renamed rather than dropped and re-added: nothing has been deployed against the
Phase 2 shape yet, so there is no data-loss concern either way, but a rename is the honest
description of what changed and costs the database nothing extra to express that way.

CHECK constraints on the new endpoint and outcome columns are NOT autogenerated by Alembic
(a documented limitation, not an oversight) and are added explicitly below.

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-17
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "kernel_call_log",
        sa.Column("case_record_id", sa.String(length=36), nullable=False),
    )
    op.create_foreign_key(
        "fk_kernel_call_log_case_record_id_case_records",
        "kernel_call_log",
        "case_records",
        ["case_record_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_index("ix_kernel_call_log_case_record_id", "kernel_call_log", ["case_record_id"])

    op.add_column(
        "kernel_call_log",
        sa.Column("kernel_base_url", sa.String(length=255), nullable=False),
    )
    op.add_column(
        "kernel_call_log",
        sa.Column("outcome", sa.String(length=20), nullable=False),
    )
    op.add_column("kernel_call_log", sa.Column("error_code", sa.String(length=20), nullable=True))
    op.add_column(
        "kernel_call_log", sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True)
    )

    op.alter_column(
        "kernel_call_log",
        "endpoint",
        existing_type=sa.String(length=60),
        type_=sa.String(length=20),
        existing_nullable=False,
    )
    op.alter_column("kernel_call_log", "created_at", new_column_name="started_at")

    op.drop_index("ix_kernel_call_log_facility_created", table_name="kernel_call_log")
    op.create_index(
        "ix_kernel_call_log_facility_started", "kernel_call_log", ["facility_id", "started_at"]
    )

    op.create_check_constraint(
        "ck_kernel_call_log_endpoint", "kernel_call_log", "endpoint IN ('ASSESS', 'EVALUATE')"
    )
    op.create_check_constraint(
        "ck_kernel_call_log_outcome",
        "kernel_call_log",
        "outcome IN ('SUCCESS', 'TIMEOUT', 'UNREACHABLE', 'KERNEL_ERROR', 'PAYLOAD_REJECTED', "
        "'MALFORMED_RESPONSE', 'CIRCUIT_OPEN', 'PHI_REJECTED')",
    )


def downgrade() -> None:
    op.drop_constraint("ck_kernel_call_log_outcome", "kernel_call_log", type_="check")
    op.drop_constraint("ck_kernel_call_log_endpoint", "kernel_call_log", type_="check")

    op.drop_index("ix_kernel_call_log_facility_started", table_name="kernel_call_log")
    op.create_index(
        "ix_kernel_call_log_facility_created", "kernel_call_log", ["facility_id", "created_at"]
    )

    op.alter_column("kernel_call_log", "started_at", new_column_name="created_at")
    op.alter_column(
        "kernel_call_log",
        "endpoint",
        existing_type=sa.String(length=20),
        type_=sa.String(length=60),
        existing_nullable=False,
    )

    op.drop_column("kernel_call_log", "completed_at")
    op.drop_column("kernel_call_log", "error_code")
    op.drop_column("kernel_call_log", "outcome")
    op.drop_column("kernel_call_log", "kernel_base_url")

    op.drop_index("ix_kernel_call_log_case_record_id", table_name="kernel_call_log")
    op.drop_constraint(
        "fk_kernel_call_log_case_record_id_case_records", "kernel_call_log", type_="foreignkey"
    )
    op.drop_column("kernel_call_log", "case_record_id")
