"""Widen kernel_reports.inference_source's CHECK to accept UNAVAILABLE.

Closes a defect in the H-09 kernel-mock production safety fix (2026-08-20, PR #12). That fix
added InferenceSource.UNAVAILABLE to the Android enum and started stamping it on every
staging/prod assessment whose real call failed and had no fallback (the honest failure state).
SyncRecordMappers.kt sends this value on the wire as inferenceSource, but this table's CHECK
constraint (ck_kernel_reports_ck_kernel_reports_inference_source, from 0002_clinical_tables.py)
only allowed 'REAL_INFERENCE' and 'MOCK_FALLBACK'.

Consequence: every UNAVAILABLE-stamped kernel report was rejected at the database with an
IntegrityError, which app/services/sync.py turns into a generic SAMD-SYNC-6003 per-record
rejection. Android maps a rejected push result to SyncState.FAILED, which by design never
retries (see EvaluateReportDao.kt's KDoc on the same FAILED state for the evaluate table). So
every honest unavailable-assessment record was permanently unsynced and inflated the
failed-sync-count badge, with no path to recovery short of this migration.

The constraint name is doubled (ck_kernel_reports_ck_kernel_reports_inference_source) because
0002 was autogenerated: NAMING_CONVENTION in app/db/base.py is "ck_%(table_name)s_%(constraint_name)s",
and the model's enum_check() call already passes a name of "ck_kernel_reports_inference_source",
so the convention wraps it a second time. Recreating under the same name here so a fresh
autogenerate diff against the now-three-member InferenceSource enum in app/models/enums.py stays
a no-op.

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-20
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_CONSTRAINT_NAME = "ck_kernel_reports_ck_kernel_reports_inference_source"


def upgrade() -> None:
    # op.f() marks the name as already fully resolved. Without it, Alembic runs the literal
    # string through NAMING_CONVENTION a second time (this context's target_metadata carries
    # it), doubling an already-doubled name into a 63-byte-overflow hash that does not match
    # what is actually in the database, and DROP CONSTRAINT fails with UndefinedObjectError.
    op.drop_constraint(op.f(_CONSTRAINT_NAME), "kernel_reports", type_="check")
    op.create_check_constraint(
        op.f(_CONSTRAINT_NAME),
        "kernel_reports",
        "inference_source IN ('REAL_INFERENCE', 'MOCK_FALLBACK', 'UNAVAILABLE')",
    )


def downgrade() -> None:
    op.drop_constraint(op.f(_CONSTRAINT_NAME), "kernel_reports", type_="check")
    op.create_check_constraint(
        op.f(_CONSTRAINT_NAME),
        "kernel_reports",
        "inference_source IN ('REAL_INFERENCE', 'MOCK_FALLBACK')",
    )
